version: '3.8'

services:
  app:
    build: .
    ports:
      - "${SERVER_PORT:-8080}:8080"
    environment:
      - DB_URL=jdbc:postgresql://db:5432/wallet
      - DB_USERNAME=${DB_USERNAME:-postgres}
      - DB_PASSWORD=${DB_PASSWORD:-postgres}
      - SERVER_PORT=8080
      - INITIAL_BALANCE=0
      - MAX_CONCURRENT_OPERATIONS=1000
    depends_on:
      - db
    networks:
      - wallet-network

  db:
    image: postgres:15-alpine
    ports:
      - "${DB_PORT:-5432}:5432"
    environment:
      - POSTGRES_DB=wallet
      - POSTGRES_USER=${DB_USERNAME:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-postgres}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - wallet-network

volumes:
  postgres-data:

networks:
  wallet-network:
    driver: bridge 