spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/wallet}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml

server:
  port: ${SERVER_PORT:8080}

app:
  wallet:
    initial-balance: ${INITIAL_BALANCE:0}
    max-concurrent-operations: ${MAX_CONCURRENT_OPERATIONS:1000} 